language: node_js
node_js:
- 12
services:
- docker
env:
  matrix:
  - NODE_ENV="production"
  DOCKER_USERNAME:
    secure: nCw9rz4Pz7haQrB15ht7xm5gBwNOEMOCKLCuI33wrs3SjhXTyXAL+jrUvV2p8gi+LvVwGtNkxzSzgzrq3o1HRAG+QQfPRmF5WqFZzTaWP1KbOavHO15x+uCnyfAwXqd5U6CQ/5P7DIVwLdUu+wMG3tNFbtF2O9hSjNuUUT6lRx+d44onLDPxXdhwYO/uyGEfin+ugWVUpcIfl5MNmQY1XLFl6I9YJT8g1Vx/FPa7M8a8KX95h+Z6/f40TUpABZ0K5GoPyqD2bCbDDl50vUQiZo1ZeqRqOuNCrsP+1jzU31DBHC4zpqWMXRGGzJ7b/O4hIJDDbBfKm+vVABGjRgNmkhgSihRmSxPdg90RVazxjR4JlcDkmWzg2jdpw7Q49cgDJcDprolOu4ynFOGuKtQ8q2/FRNWqQLceHHrdKgfQ5TepxbrkBfEB7i2T5cc/eBJ30U6UFw6OP9XNJSRLqCuC2ATwGgZclcnjoVed/oV9vT0zOIYHQUhdpZTd8trJ5gE788DC1suvf78U0zs/iENZT9s1fZE5bhskdkUH3Mnq4LSKoIZBSTgvCft1/+YeE/UrBflx+rBdLEzYJtIZLsTchAZOjoSB2V9KwuNB+wM7soIolhlEU4lUIbuSaphot5o+c32ymYAqwGc2axlBKxFnKZwgQC1ee5PsMg6QB5rGvTE=
  DOCKER_PASSWORD:
    secure: Y1XUTpaTuBMDxPTAokIhoy+nXHPpg7F2UqYnPQMidYN6t6U2JCWIesyFp7Kbm2OH+h+yXvEi4XoUzQnAGnaPIPTuMHKxpdKHgNct8hPKQlg2EBz1URAgW6x3a1WqqWLuDvRQzy2o0qtjbiv7TU4yCPEFuPOW90CMvA7c32Iv5ECKL3KJYtzmmbvDMOecGETN58Zk63Z4lEkNgR78lFQAOfA6c1+yMz+bRkyusxcahtyHlHakhsSAkDaWYTjUpHNFSvj2syE2SRP9uyqN8wG3JqNBmgQY9kA8QKs0eHBPFkeFJzkKfDK+lFcTwQxGkiWrMnSxUqmfRJ4SXCJvBj70LSWPXQHesFLEQRFOSsyBFAqyMui+17SJmU3czIycyNc+rLmE1P/X+34GsOfob0O/b6/4q5R9ZPDdBox7vENCbB5SR8LLtvzf3zb13OvaTaDd9cBF5hqqAl1HvDMpHkPvAet6cKKCg9b8ykAvD4tjb/Bc+U2u2a05EfmZ+Y60HvZe6pvTU1+X8hZykrSZW8aIs5D9Vf7fMxxNB/8GdeSLgYZgWDHGO7SbKTDfeNwFlHLAQJbErhruUSzfOzXTfllRsg9z/4CahjL4sV0hdIZVty0KfWG4dMmjmnrgJ2sR8172x1pXNk0oC2TT4R7KoFvKnNYgXo1AYKiz+oPmWy5/WIg=
install:
- npm install
- npm install -g eslint
- npm install -g mocha
script:
- npm test
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t kemarskiy/color-pick:1.0 .
- docker push kemarskiy/color-pick
