language: node_js
node_js:
- 12
services:
- docker
env:
- NODE_ENV=production USER=nikita HOST=77.47.209.52 PORT=2222
addons:
  ssh_known_hosts:
  - 77.47.209.52:2222
install:
- npm install
- npm install -g eslint
- npm install -g mocha
script:
- npm test
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t kemarskiy/color-pick:1.0 .
- docker push kemarskiy/color-pick
before_install:
- openssl aes-256-cbc -K $encrypted_8a8f606118a6_key -iv $encrypted_8a8f606118a6_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp deploy_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
